version: "3.8"
services:
  api:
    build: .
    container_name: 'api'
    image: 'api:v1'
    command: >
      sh -c 'cd src &&
             poetry run uvicorn app:app --port 8000 --host 0.0.0.0 --reload'
    networks:
      - backend
    ports:
      - '8080:8000'
    volumes:
      - ./src:/service/src
      - ./tests:/service/tests
    env_file:
      - ./env/.app.env
    restart: unless-stopped
    depends_on:
      - pgadmin4

  pgadmin4:
    image: dpage/pgadmin4:8.1
    container_name: pgadmin4
    networks:
      - backend
    ports:
      - '8888:80'
    env_file:
      - ./env/.pgadmin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    networks:
      - backend
    env_file:
      - ./env/.db.env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data:

networks:
  backend: